### ISSUE TITLE
Client not Reaching Server

### ISSUE THREAD

**Issue by yaroubh** [DomGarguilo/CardGameOfWar#1]
After compiling everything, I followed the README by launching server first (then selecting default port), and then launching 2 separate clients through two different terminal windows where I used localhost and the same port entered for the server.

The server returned the following, "Ok, we're up and running on port: 1337 ..." and after entering the appropriate IP and ports for the two clients, I selected yes for automatic card flipping and both client terminals returned "Autoflip enabled" and then leave me at a blank line. I would get no update on the server terminal saying a player has joined based on what I read from the code. 

Seems like server and client(s) are not connecting properly. Not sure if I am doing something wrong (although I followed the README very closely and carefully) or if there is a broken piece in the code.

**Comment by DomGarguilo** [comment]
It has been a while since I have looked at the code but I also tried following the instructions outlined in the README with the same result.

Looking into this now.

**Comment by DomGarguilo** [comment]
Fixed via 4bd94770cbfbd4c3a098f9104d3afa43aa9c1eb3
